version: '3'

services:
  back:
    container_name: 'back'
    build:
      dockerfile: docker/Dockerfile-back
      context: .
    ports:
      - '5001:5000'

  front:
    container_name: 'front'
    build:
      dockerfile: docker/Dockerfile-front
      context: .

    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3001:3000'
